### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by phoenixatom** [write-mv/write.mv-issues-and-features#16]
RSS feed for user's blog with /feed prefix to blog url

**Comment by boring-dragon** [comment]
There is already that feature enabled I haven't added to the meta yet. 
https://write.mv/jinas/feed

Thanks for the API suggestion. I am planning to work on it soon : )). for now, just gonna keep this issue open so I don't forget 😅

**Comment by boring-dragon** [comment]
Rss feed is done so i am closing this issue.. and opened a new one for developer APi
